name: collect-metadata

on: 
  push:
    branches: 
      - setup-workflow-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repo   
        uses: actions/checkout@v1
        with:
          repository: Homebrew/homebrew-core
      - name: Continue
        run: |
          ls -l
          cd homebrew-core
          ls -l
